Add volume clone resource and data source
powervs-ibm/terraform-provider-ibm pull request #11
Opened 2023-10-25 05:43 UTC by dhirendersingh19

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-10-25 17:58 UTC, michaelkad requested changes

2023-10-25 17:58 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_clone_async.go
> +		if *volClone.Status == "completed" {
```suggestion
		if *volClone.Status == PIVolumeCloneDone {
```

2023-10-25 18:10 UTC, dhirendersingh19 commented on ibm/service/power/data_source_ibm_pi_volume_clone_task.go
file renamed

2023-10-25 18:10 UTC, dhirendersingh19 commented on ibm/service/power/resource_ibm_pi_volume_clone_async.go
file renamed

2023-10-25 18:10 UTC, dhirendersingh19 commented on ibm/service/power/resource_ibm_pi_volume_clone_async.go
> +		if *volClone.Status == "completed" {
done

2023-10-26 14:49 UTC, michaelkad approved these changes
Looks good!

2023-12-11 15:34 UTC, powervs-ibm submitted a review, later dismissed
Looks good -- Just have to resolve conflicts. After GA you can push those changes to the main repo.

2023-12-14 18:35 UTC, powervs-ibm commented
@dhirendersingh19 do update power-go-client to v1.5.6 and push your changes to the main repo. SB has pushed to prod today.

2024-02-01 01:06 UTC, michaelkad commented
This have been merged already, closing.

2024-02-01 01:06 UTC, closed without merging