Add replication_pool_map to disaster recovery data sources
powervs-ibm/terraform-provider-ibm pull request #147
Opened 2024-08-05 16:59 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

pi_disaster_recovery_location:

```
=== RUN   TestAccIBMPIDisasterRecoveryLocationDataSourceBasic
--- PASS: TestAccIBMPIDisasterRecoveryLocationDataSourceBasic (5.74s)
PASS
```

pi_disaster_recovery_locations:

```
=== RUN   TestAccIBMPIDisasterRecoveryLocationsDataSourceBasic
--- PASS: TestAccIBMPIDisasterRecoveryLocationsDataSourceBasic (6.35s)
PASS
```

Description: Added replication_pool_map attribute to pi_disaster_recovery_location and  pi_disaster_recovery_locations datasources.

2024-08-05 20:09 UTC, michaelkad requested changes
I have left few comments that need to be addressed.

2024-08-05 20:09 UTC, michaelkad commented on website/docs/d/pi_disaster_recovery_location.html.markdown
> +  - `replication_pool_map` - (List) List of maps containing information about volume and replica pools
```suggestion
  - `replication_pool_map` - (List) List of replication pool map.
```

2024-08-05 20:09 UTC, michaelkad commented on website/docs/d/pi_disaster_recovery_location.html.markdown
> +    - `volume_pool` - (String) Pool where main volume is located
```suggestion
    - `remote_pool` - (String) Remote pool.
    - `volume_pool` - (String) Volume pool.
```

2024-08-05 20:09 UTC, michaelkad commented on website/docs/d/pi_disaster_recovery_locations.html.markdown
> +          - `volume_pool` - (String) Pool where main volume is located
Same as above

2024-08-12 22:06 UTC, michaelkad approved these changes
Lgtm

2024-08-26 18:02 UTC, ismirlia approved these changes

2024-09-23 15:57 UTC, closed without merging