Add gsr attributes to pi volume group data sources and related
powervs-ibm/terraform-provider-ibm pull request #148
Opened 2024-08-05 19:33 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

pi_volume_group (d):

=== RUN   TestAccIBMPIVolumeGroupDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupDataSource_basic (10.44s)
PASS

pi_volume_groups (d):

=== RUN   TestAccIBMPIVolumeGroupsDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupsDataSource_basic (13.01s)
PASS

pi_volume_group_details (d):

=== RUN   TestAccIBMPIVolumeGroupDetailsDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupDetailsDataSource_basic (8.56s)
PASS

pi_volume_groups_details (d):

=== RUN   TestAccIBMPIVolumeGroupsDetailsDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupsDetailsDataSource_basic (15.04s)
PASS

Description: 
Adds attributes storage_pool, replication_sites, and auxiliary as attributes to pi_volume_group, pi_volume_groups, pi_volume_group_details, and pi_volume_groups_details data sources.

2024-08-05 20:23 UTC, michaelkad requested changes
Few comments

2024-08-05 20:23 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_volume_group.go
> +				Elem:        &schema.Schema{Type: schema.TypeString},
```suggestion
			Attr_ReplicationSites: {
				Computed:    true,
				Description: "List of Replication Sites.",
				Elem:        &schema.Schema{Type: schema.TypeString},
				Type:        schema.TypeList,
```

2024-08-05 20:23 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_volume_group_details.go
> +			},
Could you sort them in an alphabetical order?

2024-08-05 20:23 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_volume_groups.go
> +						},
same as above

2024-08-05 20:23 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_volume_groups_details.go
> +						},
same as above.

2024-08-05 20:23 UTC, michaelkad commented on website/docs/d/pi_volume_group_details.html.markdown
> +- `replication_sites` - ([]String) List of replication sites for the volume group.
```suggestion
- `replication_sites` - (List) List of replication sites for the volume group.
```

2024-08-05 20:23 UTC, michaelkad commented on website/docs/d/pi_volume_groups.html.markdown
> +  - `replication_sites` - ([]String) List of replication sites for the volume group.
```suggestion
  - `replication_sites` - (List) List of replication sites for the volume group.
```

2024-08-05 20:23 UTC, michaelkad commented on website/docs/d/pi_volume_groups_details.html.markdown
> +  - `replication_sites` - ([]String) List of replication sites for the volume group.
```suggestion
  - `replication_sites` - (List) List of replication sites for the volume group.
```

2024-08-05 20:23 UTC, michaelkad commented on website/docs/r/pi_volume_group.html.markdown
> +- `replication_sites` - ([]String) List of replication sites for the volume group.
```suggestion
- `replication_sites` - (List) List of replication sites for the volume group.
```

2024-08-12 22:13 UTC, michaelkad reviewed
Few more comments.

2024-08-12 22:13 UTC, michaelkad commented on website/docs/d/pi_volume_group_details.html.markdown
> +- `storage_pool` - (String) Storage pool the volume group.
```suggestion
- `storage_pool` - (String) Storage pool of the volume group.
```

2024-08-12 22:13 UTC, michaelkad commented on website/docs/d/pi_volume_groups.html.markdown
> +  - `storage_pool` - (String) Storage pool the volume group.
```suggestion
  - `storage_pool` - (String) Storage pool of the volume group.
```

2024-08-12 22:13 UTC, michaelkad commented on website/docs/d/pi_volume_groups_details.html.markdown
> +  - `storage_pool` - (String) Storage pool the volume group.
```suggestion
  - `storage_pool` - (String) Storage pool of the volume group.
```

2024-08-12 22:13 UTC, michaelkad commented on website/docs/r/pi_volume_group.html.markdown
> +- `storage_pool` - (String) Storage pool the volume group.
```suggestion
- `storage_pool` - (String) Storage pool of the volume group.
```

2024-08-15 17:02 UTC, michaelkad requested changes
Update  for `resource_ibm_pi_volume_group` are missing

2024-08-16 21:51 UTC, michaelkad approved these changes

2024-08-26 18:33 UTC, ismirlia approved these changes

2024-08-27 20:57 UTC, Alexander-Kita commented
@michaelkad Re-requesting review for replication sites attribute checking

2024-08-28 19:40 UTC, michaelkad commented on website/docs/r/pi_volume_group.html.markdown
> +- `volume_group_name` - (String) The name of the volume group.
I don't think this is needed or set in the code.

2024-08-28 19:49 UTC, michaelkad approved these changes
lgtm

2024-09-19 20:35 UTC, michaelkad approved these changes

2024-09-23 16:13 UTC, Alexander-Kita commented
Opened in main repo.

2024-09-23 16:13 UTC, closed without merging