Granular CRN for network datasources and resources
powervs-ibm/terraform-provider-ibm pull request #162
Opened 2024-08-20 20:27 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-08-22 14:28 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_network.go
> +	}
Could check the Len()>0 before expanding?

2024-08-22 14:29 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_network_port_attach.go
> +	}
Same as above

2024-08-22 14:30 UTC, michaelkad requested changes
Left few comments

2024-08-26 21:35 UTC, ismirlia approved these changes

2024-09-05 14:09 UTC, michaelkad approved these changes

2024-09-06 18:09 UTC, michaelkad approved these changes

2024-09-17 19:37 UTC, Alexander-Kita commented
Opened in main repo

2024-09-17 19:37 UTC, closed without merging