Granular CRN for instance datasources and resources
powervs-ibm/terraform-provider-ibm pull request #163
Opened 2024-08-20 20:27 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-08-22 14:39 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_instance.go
> +				Description: "List of user tags.",
This should be right next to `Arg_UserData` in the arguments section above

2024-08-22 14:39 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_instance.go
> +			},
This should be right next to `Arg_UserData` in the arguments section above

2024-08-22 14:40 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_instance.go
> +			},
This should be in `// Attributes` section below

2024-08-22 14:41 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_instance.go
> +	}
Could you check for `Len()> 0` before expanding it?

2024-08-22 14:42 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_instance.go
> +	}
Same as above comment

2024-08-22 14:42 UTC, michaelkad requested changes
Few comments.

2024-08-27 22:19 UTC, ismirlia approved these changes

2024-09-06 18:11 UTC, michaelkad approved these changes

2024-09-11 18:45 UTC, michaelkad approved these changes

2024-09-17 19:34 UTC, Alexander-Kita commented
Opened in main repo

2024-09-17 19:34 UTC, closed without merging