Granular CRN for image datasources and resources
powervs-ibm/terraform-provider-ibm pull request #164
Opened 2024-08-20 20:28 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-08-22 14:45 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_catalog_images.go
> +							Description: "CRN of resource.",
```suggestion
							Description: "CRN of this resource.",
```

2024-08-22 14:46 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_catalog_images.go
> +
Could you add a check for if we have that value or not? And then set it.

2024-08-22 14:47 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_image.go
> +				Description: "CRN of image.",
```suggestion
				Description: "CRN of the image.",
```

2024-08-22 14:48 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_images.go
> +							Description: "CRN of image.",
```suggestion
							Description: "CRN of the image.",
```

2024-08-22 14:50 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_image.go
> +		}
Could add this `body.UserTags= userTags`? And check `if len() >0` first

2024-08-22 14:52 UTC, michaelkad requested changes
Few comments.

2024-08-30 18:22 UTC, ismirlia approved these changes

2024-09-06 18:03 UTC, michaelkad approved these changes

2024-09-13 16:29 UTC, michaelkad approved these changes

2024-09-17 19:32 UTC, Alexander-Kita commented
Opened in main repo

2024-09-17 19:32 UTC, closed without merging