Granular CRN for dedicated host resources and data sources
powervs-ibm/terraform-provider-ibm pull request #165
Opened 2024-08-20 20:29 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-08-22 14:54 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_host.go
> +	}
Since that is an array could check the `if len() > 0` instead?

2024-08-22 14:55 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_hosts.go
> +							Description: "CRN of host.",
```suggestion
							Description: "CRN of the host.",
```

2024-08-22 15:00 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_host.go
> +			UserTags:    flex.ExpandStringList(host[Attr_UserTags].([]interface{})),
You might want to check if the `len()>0` then set `hs. UserTags`

2024-08-22 15:04 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_host_group.go
> +	host.UserTags = flex.ExpandStringList(modelMap[Attr_UserTags].([]interface{}))
Could you add a check for `userTags`?

2024-08-22 15:07 UTC, michaelkad commented on website/docs/r/pi_host.html.markdown
> +* `pi_user_tags` - (Optional, String) List of user tags for the host.
This should be inside `pi_host` and as `user_tags`

2024-08-22 15:08 UTC, michaelkad requested changes
Few comments

2024-10-31 18:19 UTC, ismirlia approved these changes

2024-11-18 20:42 UTC, michaelkad approved these changes

2025-02-03 15:30 UTC, michaelkad submitted a review, later dismissed

2025-02-12 17:44 UTC, michaelkad approved these changes

2025-02-12 17:58 UTC, Alexander-Kita commented
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5983

2025-02-12 17:58 UTC, closed without merging