Catalog-refactor images
powervs-ibm/terraform-provider-ibm pull request #23
Opened 2023-12-28 16:17 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-01-03 22:11 UTC, michaelkad reviewed
LGTM

2024-01-05 16:06 UTC, ismirlia submitted a review, later dismissed

2024-01-05 16:07 UTC, ismirlia commented
I think this looks good, if @michaelkad approves, open the PR in the main terraform repo for merging there.

2024-01-05 16:59 UTC, michaelkad requested changes
Just one thing

2024-01-05 16:59 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	//Arg_CloudInstanceID                 = "pi_cloud_instance_id"
This is in line 8 and should be removed

2024-01-05 22:12 UTC, ismirlia approved these changes

2024-01-05 23:00 UTC, michaelkad approved these changes

2024-01-09 21:33 UTC, ismirlia commented
@Diptipowervs Since @michaelkad approved now could you open this pull request in the main terraform provider repo to get this ready to merge?

2024-01-31 18:35 UTC, Diptipowervs commented
PR opened in main

2024-01-31 18:35 UTC, closed without merging