Add powerEdgeRouter Status
powervs-ibm/terraform-provider-ibm pull request #52
Opened 2024-01-10 05:50 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-01-10 15:52 UTC, ismirlia commented on ibm/service/power/ibm_pi_constants.go
> +	Attr_powerEdgeRouterStatus = "pi_powerEdgeRouterStatus"
Please stylize the name the same way as the other variables.
"Attr_PowerEdgeRouterStatus"

2024-01-10 17:48 UTC, michaelkad requested changes
~This PR should be set to draft, since it is not completed yet. 
Those files will be needed
`go.mod, go.sum`~

2024-02-21 11:20 UTC, Diptipowervs commented
--- PASS: TestAccIBMPIWorkspacesDataSourceBasic (233.96s)
PASS

2024-02-22 16:58 UTC, michaelkad requested changes
That is map not a string

2024-02-22 16:58 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_workspace.go
> +			},
This is a map

``  "powerEdgeRouter":{
         "type": "automated" | "manual",
         "state": "active" | "error" | "warning" | "configuring" | "removing" | "inactive",
         "migrationStatus": "initializing" | "migrating " | "deleted" | "complete"
     }``

2024-02-23 16:51 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	Attr_PowerEdgeRouterStatus                       = "pi_power_edge_router_status"
```suggestion
	Attr_PowerEdgeRouter                      = "power_edge_router"
```

2024-02-23 16:52 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_workspace.go
> +	d.Set(Attr_PowerEdgeRouterStatus, wsData.Details.PowerEdgeRouter.MigrationStatus)
```suggestion
	wsdetails := map[string]interface{}{
 		Attr_CreationDate: wsData.Details.CreationDate.String(),
 		Attr_CRN:          *wsData.Details.Crn,
 		Attr_PowerEdgeRouter: <-- map object with migration, state, type
	}
```

2024-02-29 09:52 UTC, Diptipowervs commented
--- PASS: TestAccIBMPIWorkspacesDataSourceBasic (100.16s)
PASS
--- PASS: TestAccIBMPIWorkspaceDataSourceBasic (34.43s)
PASS

2024-02-29 21:32 UTC, ismirlia commented
This might be overly nit-picky, but there's already constants defined for the string "status" and "type," "Attr_Status", "Attr_Type".

In my view the constant names should be Arg_ or Attr_ prepended to camel case value. For example, "source_volume_name" becomes Attr_SourceVolumeName.

To me the goal of the refactor is just to cut down on the amount of duplicate text. To have a variable like Attr_PowerEdgeRouterState for the string "status" feels redundant to me when 
      a. another constant with that value already exists
      b. to anyone reading the code it should be become very quickly apparent that status in this case is part of the power edge router map.

2024-03-01 18:34 UTC, michaelkad requested changes
Could you add this  to the workspaces as well and update the docs please

2024-03-01 18:34 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	Attr_PowerEdgeRouterType                         = "type"
```suggestion
	Attr_State                        = "state"
	Attr_Type                         = "type"
```

2024-03-01 19:52 UTC, michaelkad commented on ibm/service/power/data_source_ibm_pi_workspace.go
> +			},
This is can be deleted since it is nested inside ws_details

2024-03-04 23:19 UTC, powervs-ibm commented on ibm/service/power/data_source_ibm_pi_workspace.go
>  	}
```suggestion
	wsDetails := map[string]interface{}{}
	wsDetails[Attr_CreationDate] = wsData.Details.CreationDate.String()
	wsDetails[Attr_CRN] = *wsData.Details.Crn
```

2024-03-04 23:20 UTC, powervs-ibm commented on ibm/service/power/data_source_ibm_pi_workspace.go
> +		wsDetails[Attr_PowerEdgeRouter] = wsPowerEdgeList
```suggestion
		wsDetails[Attr_PowerEdgeRouter] =  []map[string]interface{}{wsPowerEdge}
```

2024-03-04 23:28 UTC, ismirlia commented
Messed up branch closing

2024-03-04 23:28 UTC, closed without merging

2024-03-04 23:32 UTC, powervs-ibm commented on ibm/service/power/data_source_ibm_pi_workspace.go
>  	}
#72

2024-03-04 23:32 UTC, powervs-ibm commented on ibm/service/power/data_source_ibm_pi_workspace.go
> +		wsDetails[Attr_PowerEdgeRouter] = wsPowerEdgeList
#72