Add return crn attribute
powervs-ibm/terraform-provider-ibm pull request #54
Opened 2024-01-19 09:37 UTC by Diptipowervs

This in response to: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5061

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-01-19 17:01 UTC, michaelkad requested changes
You have to update the doc as well

2024-01-19 17:01 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_workspace.go
> +		WorkspaceCRN:          controller.CRN,
This should be the targetcrn double check that when you ran it
```suggestion
		WorkspaceCRN:          controller.TargetCRN,
```

2024-01-27 00:30 UTC, michaelkad commented on website/docs/d/pi_workspace.html.markdown
> +  - `crn` - (String) Workspace Target crn.
```suggestion
  - `crn` - (String) Workspace  crn.
```

2024-01-27 00:31 UTC, michaelkad commented on website/docs/d/pi_workspace.html.markdown
> +  - `crn` - (String) Workspace Target crn.
The description doesn't need to change.

2024-01-27 00:32 UTC, michaelkad requested changes
One last comment!

2024-02-01 01:02 UTC, michaelkad submitted a review, later dismissed

2024-03-04 23:30 UTC, closed without merging

2024-03-04 23:30 UTC, ismirlia commented
This has been merged in the main terraform repo closing...