Refactor resource capture
powervs-ibm/terraform-provider-ibm pull request #60
Opened 2024-02-20 19:48 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-21 04:22 UTC, Diptipowervs commented
--- PASS: TestAccIBMPICaptureBasic (67.31s)
PASS

2024-03-25 21:52 UTC, michaelkad requested changes

2024-03-25 21:52 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	Arg_InstanceName                         = "pi_instance_name"
All those should be name just like `Arg_InstanceName`
Prefix+Camel case
this: `Arg_InstanceCaptureCloudStorageAccessKey = "pi_capture_cloud_storage_access_key"` should be Arg_CaptureCloudStorageAccessKey = "pi_capture_cloud_storage_access_key"

2024-03-25 21:52 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	Arg_VTL                                  = "vtl"
This should be at the bottom

2024-05-28 16:50 UTC, michaelkad commented
Opened #128

2024-05-28 16:50 UTC, closed without merging