Refactor resource image and documentation
powervs-ibm/terraform-provider-ibm pull request #66
Opened 2024-02-25 21:38 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-11 21:19 UTC, ismirlia commented on ibm/service/power/resource_ibm_pi_image.go
> +		Pending: []string{Arg_JobStatusQueued, Arg_JobStatusReadyForProcessing, Arg_JobStatusInProgress, Arg_JobStatusRunning, Arg_JobStatusWaiting},
So these aren't arguments to the terraform resource, and the value of them should not be changed. Make a new section for the status constants. Something like:

```
Status_Queued = "queued"
Status_InProgress = "in_progress"
...
```

2024-03-25 21:38 UTC, michaelkad requested changes
Const updated incorrectly.

2024-03-25 21:38 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_image.go
> +		Pending:    []string{"retry", Image_Questatus},
`PIImageQueStatus         = "queued"`

2024-03-25 21:38 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_image.go
> +		Target:     []string{Image_ActiveStatus},
`PIImageActiveStatus      = "active"`

2024-03-25 21:38 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_image.go
> +			if *job.Status.State == Status_Failed {
`JobStatusFailed             = "failed"`

2024-05-28 19:08 UTC, michaelkad commented
Opened #130

2024-05-28 19:08 UTC, closed without merging