Refactor instance action resource and documentation
powervs-ibm/terraform-provider-ibm pull request #69
Opened 2024-02-27 10:02 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-08 15:11 UTC, michaelkad requested changes
Why is everything looks like they have been changed? I can tell what is the change here

2024-03-11 16:20 UTC, ismirlia commented on ibm/service/power/resource_ibm_pi_instance_action.go
>  			// Computed
Change computed to Attributes

2024-03-12 06:53 UTC, Diptipowervs commented on ibm/service/power/resource_ibm_pi_instance_action.go
>  			// Computed
Changed

2024-03-21 17:41 UTC, Diptipowervs commented
--- PASS: TestAccIBMPIInstanceAction (363.41s)
PASS

2024-05-10 20:47 UTC, michaelkad commented
Open #121

2024-05-10 20:47 UTC, closed without merging