Refactor resource placement group and documentation
powervs-ibm/terraform-provider-ibm pull request #83
Opened 2024-03-12 18:10 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-25 21:22 UTC, michaelkad requested changes

2024-03-25 21:22 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	PIVPNPolicyAuthentication                 = "policy_authentication"
Those have to me change to add prefix `Attr_` or `Arg_`

2024-03-25 21:22 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	PIPlacementGroupPolicy  = "policy"
Those have to me change to add prefix `Attr_` or `Arg_`

2024-03-28 10:24 UTC, Diptipowervs commented
Closing PR due to multiple conflicts. New PR https://github.com/powervs-ibm/terraform-provider-ibm/pull/104

2024-03-28 10:35 UTC, closed without merging

2024-03-28 10:36 UTC, Diptipowervs commented
closed