Refactor Resource volume attach and documentation
powervs-ibm/terraform-provider-ibm pull request #89
Opened 2024-03-18 14:48 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-25 20:23 UTC, michaelkad requested changes

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	Arg_InstanceId                          = "pi_instace_id"
Already have  `Arg_PVMInstanceId` define

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +			Arg_InstanceId: {
Use `Arg_PVMInstanceId`

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +			Attr_VolumeAttachStatus: {
This should `Attr_Status = status`

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +	if volinfo.State == Attr_VolumeAllowableAttachStatus && !*volinfo.Shareable {
The value of `PIVolumeAllowableAttachStatus     = "in-use"` need to be updated

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +	d.Set(Attr_VolumeAttachStatus, vol.State)
See above comment

2024-03-25 20:23 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +		Target:     []string{Attr_VolumeAllowableAttachStatus},
Need to update the const to be those
```
	PIVolumeProvisioning     = "creating"
	PIVolumeAllowableAttachStatus     = "in-use"
```

2024-03-28 12:04 UTC, Diptipowervs commented on ibm/service/power/resource_ibm_pi_volume_attach.go
> +			Attr_VolumeAttachStatus: {
Added

2024-05-31 17:48 UTC, michaelkad commented
Opened #133

2024-05-31 17:48 UTC, closed without merging