Refactor resource volume group action and documentation
powervs-ibm/terraform-provider-ibm pull request #91
Opened 2024-03-18 16:50 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-25 20:07 UTC, michaelkad requested changes

2024-03-25 20:07 UTC, michaelkad commented on ibm/service/power/ibm_pi_constants.go
> +	SctionReset   = "reset"
This a typo -- should have been ActionAccess ...
And move it up to after 
Arg
Attr
Status/State

2024-03-25 20:07 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_group_action.go
> +						SctionStart: {
```suggestion
						ActionStart: {
```

2024-05-31 17:48 UTC, closed without merging

2024-11-19 10:36 UTC, alphachart reviewed
.