Refactor resource volume onboarding and documentations
powervs-ibm/terraform-provider-ibm pull request #94
Opened 2024-03-18 20:28 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-03-25 19:49 UTC, michaelkad requested changes

2024-03-25 19:49 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_onboarding.go
> +			Arg_CloudInstanceID: {
```suggestion
// Arguments
			Arg_CloudInstanceID: {
```

2024-03-25 19:49 UTC, michaelkad commented on ibm/service/power/resource_ibm_pi_volume_onboarding.go
>  			piOnboardingVolumes: {
All of these should be moved to the constant file and rename with `Arg_` prefix
eg:
`Arg_OnboardingVolumes = "pi_onboarding_volumes"`
```
const (
	piOnboardingVolumes   = "pi_onboarding_volumes"
	piAuxiliaryVolumes    = "pi_auxiliary_volumes"
	piAuxiliaryVolumeName = "pi_auxiliary_volume_name"
	piSourceCRN           = "pi_source_crn"
	piDisplayName         = "pi_display_name"
	piDescription         = "pi_description"
)
```

2024-09-20 18:19 UTC, ismirlia commented
```
--- PASS: TestAccIBMPIVolumeOnboardingbasic (16.77s)
PASS
```

2024-09-20 18:57 UTC, ismirlia commented
Opened: https://github.com/powervs-ibm/terraform-provider-ibm/pull/168 closing this

2024-09-20 18:57 UTC, closed without merging